#!/bin/sh

cd /usr/share/tests

echo "=== Running tests ptest ==="

PASS=0
FAIL=0

for testscript in ./test*.sh; do
  echo "TEST: $(basename $testscript)"
  ./$testscript && PASS=$((PASS+1)) || FAIL=$((FAIL+1))
done

echo "=== Summary: $PASS passed, $FAIL failed ==="
[ $FAIL -eq 0 ] || exit 1
