BBPATH := "${BBPATH}:${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-image-tests"
BBFILE_PATTERN_meta-image-tests = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-image-tests = "6"

LAYERDEPENDS_meta-image-tests = "core"
LAYERSERIES_COMPAT_meta-image-tests = "walnascar"
