services:
  yocto:
    build:
      context: .
      dockerfile: docker/image_builder.dockerfile
      args:
        USER: "user"
        GROUP: "yoctogroup"
    image: "yocto-builder-image"
    volumes:
      - yocto-build:/home/user/poky/build
      - yocto-downloads:/home/user/poky/downloads
      - yocto-sstate:/home/user/poky/sstate-cache
      - ./conf/local.conf:/home/user/poky/build/conf/local.conf
      - ./layers/meta-image-tests:/home/user/poky/meta-image-tests
    networks:
      yocto-network:
        ipv4_address: 192.168.1.10

  python:
    build:
      context: .
      dockerfile: docker/python.dockerfile
    networks:
      yocto-network:
        ipv4_address: 192.168.1.11
    depends_on:
      - yocto

volumes:
  yocto-build:
  yocto-downloads:
  yocto-sstate:

networks:
  yocto-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
