IMAGE_INSTALL:append = " \
    auto-login \
    fio \
    fwts \
    iperf3 \
    lvm2 \
    openjdk-25-jre \
    perf \
    phoronix-test-suite \
    ptest-runner \
    stress-ng \
    sysstat \
    systemd-analyze \
"
