IMAGE_INSTALL:append = " \
    abseil-cpp \
    acl \
    attr \
    autoconf \
    auto-login \
    automake \
    base-passwd \
    bash \
    bash-completion \
    bc \
    binutils \
    bridge-utils \
    brotli \
    bzip2 \
    c-ares \
    ca-certificates \
    coreutils \
    cpio \
    cracklib \
    cronie \
    curl \
    dbus \
    debugedit \
    desktop-file-utils \
    diffutils \
    dmidecode \
    dnf \
    docker-moby \
    e2fsprogs \
    ed \
    elfutils \
    ethtool \
    expat \
    file \
    findutils \
    fuse3 \
    fwts \
    gawk \
    gcc \
    gdb \
    gdbm \
    gettext \
    git \
    glib-2.0 \
    glibc \
    glibc-dev \
    gmp \
    gnupg \
    gnutls \
    go \
    gobject-introspection \
    gpgme \
    grep \
    groff \
    gzip \
    ipmitool \
    iproute2 \
    iptables \
    iputils \
    jq \
    json-c \
    kbd \
    kmod \
    ldconfig \
    less \
    libassuan \
    libcap \
    libcap-ng \
    libcomps \
    libdnf \
    libestr \
    libfastjson \
    libffi \
    libgcc \
    libgcc-dev \
    libpcre \
    libpcre2 \
    libgcrypt \
    libgpg-error \
    libksba \
    libmnl \
    libmpc \
    libnsl2 \
    libpipeline \
    libpcap \
    librepo \
    libseccomp \
    libsolv \
    libtasn1 \
    libtirpc \
    libtool \
    libunistring \
    libusb1 \
    libxcrypt \
    libxml2 \
    libyaml \
    logrotate \
    lshw \
    lsof \
    lsscsi \
    lzip \
    lzlib \
    lzo \
    lzop \
    m4 \
    make \
    man-db \
    mc \
    mpfr \
    ncurses \
    net-snmp \
    net-tools \
    netbase \
    netcat \
    nettle \
    nginx \
    npth \
    nss-pam-ldapd \
    oath \
    onig \
    openldap \
    openssh \
    openssl \
    os-release \
    packagegroup-core-buildessential \
    packagegroup-core-tools-debug \
    parted \
    patch \
    pciutils \
    perl \
    phoronix-test-suite \
    pinentry \
    pkgconfig \
    popt \
    procps \
    protobuf \
    psmisc \
    ptest-runner \
    python3 \
    python3-packaging \
    python3-pip \
    python3-setuptools \
    readline \
    rpm \
    rsync \
    rsyslog \
    screen \
    sed \
    sg3-utils \
    shadow \
    shared-mime-info \
    socat \
    sqlite3 \
    strace \
    sudo \
    stress-ng \
    tar \
    tcpdump \
    time \
    tini \
    tmux \
    traceroute \
    udev \
    unzip \
    usbutils \
    util-linux \
    wget \
    which \
    xz \
    yq \
    zip \
    zlib \
    zstd \
    endurance-test \
    endurance-test-ptest \
    performance-test \
    performance-test-ptest \
"
