[supervisord]
nodaemon=true
user=user
logfile=/home/user/imgtests/supervisord.log
pidfile=/run/supervisord.pid

[program:migrations]
command=/bin/sh -c "python3 -m imgtests migrate"
autostart=true
autorestart=false
startsecs=0
redirect_stderr=true
stdout_logfile=/home/user/imgtests/migrations.log
stdout_logfile_maxbytes=0

[program:web]
command=/bin/sh -c "python3 -m imgtests runserver 0.0.0.0:8000"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
depends_on=migrations

[program:worker1]
command=/bin/sh -c "python3 -m imgtests db_worker"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/user/imgtests/worker1.log
stdout_logfile_maxbytes=0
depends_on=web

[program:worker2]
command=/bin/sh -c "python3 -m imgtests db_worker"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/user/imgtests/worker2.log
stdout_logfile_maxbytes=0
depends_on=web
