services:
  imgtests-yocto:
    build:
      dockerfile: docker/image_builder.dockerfile
      args:
        USER: ${USER}
        GROUP: ${GROUP}
        PASSWORD: ${PASSWORD}
        POKY_DIR: ${POKY_DIR}
    user: ${USER}:${GROUP}
    image: ${DOCKER_TAG}
    command: sleep infinity
    volumes:
      - ${DOCKER_BUILD_VOLUME}:${BUILD_DIR}
      - ${DOCKER_DOWNLOADS_VOLUME}:${POKY_DIR}/downloads
      - ${DOCKER_SSTATE_VOLUME}:${POKY_DIR}/sstate-cache
      - ${HOST_CONF_PATH}/local.conf:${BUILD_DIR}/conf/local.conf
      - ${HOST_CONF_PATH}/packages.conf:${BUILD_DIR}/conf/packages.conf
      - ${HOST_LAYERS_PATH}/meta-image-tests:${POKY_DIR}/meta-image-tests
    environment:
      SSH_USER: root
      SSH_PASS: strong
    networks:
      yocto-network:
        ipv4_address: ${YOCTO_ADDRESS}

  imgtests-analyzer:
    build:
      dockerfile: docker/python.dockerfile
      args:
        USER: ${USER}
        GROUP: ${GROUP}
    image: ${DOCKER_PYTHON_TAG}
    command: sleep infinity
    volumes:
      - ./tests/image:/home/${USER}/tests
    environment:
      SSH_USER: root
      SSH_PASS: strong
    networks:
      yocto-network:
        ipv4_address: ${PYTHON_ADDRESS}

volumes:
  imgtests-yocto-build:
  imgtests-yocto-downloads:
  imgtests-yocto-sstate:

networks:
  yocto-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
