from typing import Any

import pytest

from imgtests.exec.loaders import (
    Fio,
    Iperf3,
    Kirk,
    Perf,
    PhoronixTestSuite,
    StressNg,
)


@pytest.mark.parametrize(
    ("raw_metrics", "expected"),
    [
        (
            {
                "stress_ng_metrics": [
                    {
                        "stressor": "cpu",
                        "bogo_ops": 276,
                        "real_time_secs": 1.14,
                        "usr_time_secs": 4.14,
                        "sys_time_secs": 0.18,
                        "bogo_ops_s_real_time": 242.15,
                        "bogo_ops_s_usr_sys_time": 63.93,
                        "cpu_used_per_instance": 94.7,
                        "rss_max_kb": 6212,
                        "top10_slowest": None,
                    },
                ],
                "stress_ng_summary": {
                    "skipped": 0,
                    "passed": 4,
                    "failed": 0,
                    "metrics_untrustworthy": 0,
                },
            },
            {
                "tool": "stress-ng",
                "test_type": {
                    "stressor": "cpu",
                },
                "time": {
                    "duration_sec": 5.46,
                },
                "metrics": {
                    "0": {
                        "bogo_ops": 276,
                        "real_time_secs": 1.14,
                        "usr_time_secs": 4.14,
                        "sys_time_secs": 0.18,
                        "bogo_ops_s_real_time": 242.15,
                        "bogo_ops_s_usr_sys_time": 63.93,
                        "cpu_used_per_instance": 94.7,
                        "rss_max_kb": 6212,
                        "top10_slowest": None,
                    },
                    "summary": {
                        "skipped": 0,
                        "passed": 4,
                        "failed": 0,
                        "metrics_untrustworthy": 0,
                    },
                },
            },
        ),
        (
            {},
            {
                "tool": "stress-ng",
                "test_type": {},
                "time": {},
                "metrics": {},
            },
        ),
    ],
    ids=[
        "Stress-ng adapter test.",
        "Empty metrics.",
    ],
)
def test_stress_ng_parse_metrics(raw_metrics: dict[str, Any], expected: dict[str, Any]) -> None:
    result = StressNg.split_result(raw_metrics=raw_metrics)
    assert result == expected


@pytest.mark.parametrize(
    ("raw_metrics", "expected"),
    [
        (
            [
                {
                    "benchmark": "sched/pipe",
                    "total_time": 198.97,
                    "usecs_per_op": 198.970091,
                    "ops_per_sec": 5025,
                },
            ],
            {
                "tool": "perf",
                "test_type": {
                    "benchmark": "sched/pipe",
                },
                "time": {
                    "duration_sec": 198.97,
                },
                "metrics": {
                    "usecs_per_op": 198.970091,
                    "ops_per_sec": 5025,
                },
            },
        ),
        (
            {},
            {
                "tool": "perf",
                "test_type": {},
                "time": {},
                "metrics": {},
            },
        ),
    ],
    ids=[
        "Perf adapter test.",
        "Empty metrics.",
    ],
)
def test_perf_parse_metrics(raw_metrics: dict[str, Any], expected: dict[str, Any]) -> None:
    result = Perf.split_result(raw_metrics=raw_metrics)
    assert result == expected


@pytest.mark.parametrize(
    ("raw_metrics", "expected"),
    [
        (
            {
                "client": {
                    "start": {
                        "connected": [
                            {
                                "socket": 5,
                                "local_host": "127.0.0.1",
                                "local_port": 45538,
                                "remote_host": "127.0.0.1",
                                "remote_port": 5201,
                            },
                        ],
                        "version": "iperf 3.18",
                        "system_info": "Linux qemux86-64 6.12.47-yocto-standard x86_64",
                        "timestamp": {
                            "time": "Sun, 05 Apr 2026 22:05:53 GMT",
                            "timesecs": 1775426753,
                        },
                        "connecting_to": {"host": "localhost", "port": 5201},
                        "cookie": "dyopoldniowo2jvialnl5lwejw6wjx3bln3b",
                        "target_bitrate": 1048576,
                        "fq_rate": 0,
                        "sock_bufsize": 0,
                        "sndbuf_actual": 212992,
                        "rcvbuf_actual": 212992,
                        "test_start": {
                            "protocol": "UDP",
                            "num_streams": 1,
                            "blksize": 32768,
                            "omit": 0,
                            "duration": 1,
                            "bytes": 0,
                            "blocks": 0,
                            "reverse": 0,
                            "tos": 0,
                            "target_bitrate": 1048576,
                            "bidir": 0,
                            "fqrate": 0,
                            "interval": 1,
                        },
                    },
                    "intervals": [
                        {
                            "streams": [
                                {
                                    "socket": 5,
                                    "start": 0,
                                    "end": 1.005694,
                                    "seconds": 1.005694031715393,
                                    "bytes": 163840,
                                    "bits_per_second": 1303298.9743056642,
                                    "packets": 5,
                                    "omitted": "false",
                                    "sender": "true",
                                },
                            ],
                            "sum": {
                                "start": 0,
                                "end": 1.005694,
                                "seconds": 1.005694031715393,
                                "bytes": 163840,
                                "bits_per_second": 1303298.9743056642,
                                "packets": 5,
                                "omitted": "false",
                                "sender": "true",
                            },
                        },
                    ],
                    "end": {
                        "streams": [
                            {
                                "udp": {
                                    "socket": 5,
                                    "start": 0,
                                    "end": 1.005694,
                                    "seconds": 1.005694,
                                    "bytes": 163840,
                                    "bits_per_second": 1303299.0154062766,
                                    "jitter_ms": 0.3490292816162109,
                                    "lost_packets": 0,
                                    "packets": 5,
                                    "lost_percent": 0,
                                    "out_of_order": 0,
                                    "sender": "true",
                                },
                            },
                        ],
                        "sum": {
                            "start": 0,
                            "end": 1.006723,
                            "seconds": 1.006723,
                            "bytes": 163840,
                            "bits_per_second": 1303299.0154062766,
                            "jitter_ms": 0.3490292816162109,
                            "lost_packets": 0,
                            "packets": 5,
                            "lost_percent": 0,
                            "sender": "true",
                        },
                        "sum_sent": {
                            "start": 0,
                            "end": 1.005694,
                            "seconds": 1.005694,
                            "bytes": 163840,
                            "bits_per_second": 1303299.0154062766,
                            "jitter_ms": 0,
                            "lost_packets": 0,
                            "packets": 5,
                            "lost_percent": 0,
                            "sender": "true",
                        },
                        "sum_received": {
                            "start": 0,
                            "end": 1.006723,
                            "seconds": 1.006723,
                            "bytes": 163840,
                            "bits_per_second": 1301966.8766880264,
                            "jitter_ms": 0.3490292816162109,
                            "lost_packets": 0,
                            "packets": 5,
                            "lost_percent": 0,
                            "sender": "false",
                        },
                        "cpu_utilization_percent": {
                            "host_total": 2.7494258492000685,
                            "host_user": 0.4593206399453781,
                            "host_system": 2.291366013376162,
                            "remote_total": 1.8860973187686196,
                            "remote_user": 0.772591857000993,
                            "remote_system": 1.1143992055610725,
                        },
                    },
                },
                "server": {
                    "start": {
                        "connected": [
                            {
                                "socket": 5,
                                "local_host": "127.0.0.1",
                                "local_port": 5201,
                                "remote_host": "127.0.0.1",
                                "remote_port": 45538,
                            },
                        ],
                        "version": "iperf 3.18",
                        "system_info": "Linux qemux86-64 6.12.47-yocto-standard x86_64",
                        "target_bitrate": 1048576,
                        "timestamp": {
                            "time": "Sun, 05 Apr 2026 22:05:53 GMT",
                            "timesecs": 1775426753,
                        },
                        "accepted_connection": {"host": "127.0.0.1", "port": 33678},
                        "cookie": "dyopoldniowo2jvialnl5lwejw6wjx3bln3b",
                        "fq_rate": 0,
                        "sock_bufsize": 0,
                        "sndbuf_actual": 212992,
                        "rcvbuf_actual": 212992,
                        "test_start": {
                            "protocol": "UDP",
                            "num_streams": 1,
                            "blksize": 32768,
                            "omit": 0,
                            "duration": 1,
                            "bytes": 0,
                            "blocks": 0,
                            "reverse": 0,
                            "tos": 0,
                            "target_bitrate": 1048576,
                            "bidir": 0,
                            "fqrate": 0,
                            "interval": 1,
                        },
                    },
                    "intervals": [
                        {
                            "streams": [
                                {
                                    "socket": 5,
                                    "start": 0,
                                    "end": 1.000781,
                                    "seconds": 1.0007810592651367,
                                    "bytes": 131072,
                                    "bits_per_second": 1047757.6391882942,
                                    "jitter_ms": 0.327097900390625,
                                    "lost_packets": 0,
                                    "packets": 4,
                                    "lost_percent": 0,
                                    "omitted": "false",
                                    "sender": "false",
                                },
                            ],
                            "sum": {
                                "start": 0,
                                "end": 1.000781,
                                "seconds": 1.0007810592651367,
                                "bytes": 131072,
                                "bits_per_second": 1047757.6391882942,
                                "jitter_ms": 0.327097900390625,
                                "lost_packets": 0,
                                "packets": 4,
                                "lost_percent": 0,
                                "omitted": "false",
                                "sender": "false",
                            },
                        },
                        {
                            "streams": [
                                {
                                    "socket": 5,
                                    "start": 1.000781,
                                    "end": 1.006723,
                                    "seconds": 0.005942000076174736,
                                    "bytes": 32768,
                                    "bits_per_second": 44117131.713125065,
                                    "jitter_ms": 0.3490292816162109,
                                    "lost_packets": 0,
                                    "packets": 1,
                                    "lost_percent": 0,
                                    "omitted": "false",
                                    "sender": "false",
                                },
                            ],
                            "sum": {
                                "start": 1.000781,
                                "end": 1.006723,
                                "seconds": 0.005942000076174736,
                                "bytes": 32768,
                                "bits_per_second": 44117131.713125065,
                                "jitter_ms": 0.3490292816162109,
                                "lost_packets": 0,
                                "packets": 1,
                                "lost_percent": 0,
                                "omitted": "false",
                                "sender": "false",
                            },
                        },
                    ],
                    "end": {
                        "streams": [
                            {
                                "udp": {
                                    "socket": 5,
                                    "start": 0,
                                    "end": 1.006723,
                                    "seconds": 1.006723,
                                    "bytes": 0,
                                    "bits_per_second": 0,
                                    "jitter_ms": 0.3490292816162109,
                                    "lost_packets": 0,
                                    "packets": 5,
                                    "lost_percent": 0,
                                    "out_of_order": 0,
                                    "sender": "false",
                                },
                            },
                        ],
                        "sum": {
                            "start": 0,
                            "end": 1.006723,
                            "seconds": 1.006723,
                            "bytes": 0,
                            "bits_per_second": 0,
                            "jitter_ms": 0.3490292816162109,
                            "lost_packets": 0,
                            "packets": 5,
                            "lost_percent": 0,
                            "sender": "false",
                        },
                        "sum_sent": {
                            "start": 0,
                            "end": 1.006723,
                            "seconds": 1.006723,
                            "bytes": 0,
                            "bits_per_second": 0,
                            "jitter_ms": 0,
                            "lost_packets": 0,
                            "packets": 0,
                            "lost_percent": 0,
                            "sender": "true",
                        },
                        "sum_received": {
                            "start": 0,
                            "end": 1.006723,
                            "seconds": 1.006723,
                            "bytes": 163840,
                            "bits_per_second": 1301966.8766880264,
                            "jitter_ms": 0.3490292816162109,
                            "lost_packets": 0,
                            "packets": 5,
                            "lost_percent": 0,
                            "sender": "false",
                        },
                        "cpu_utilization_percent": {
                            "host_total": 1.8860973187686196,
                            "host_user": 0.772591857000993,
                            "host_system": 1.1143992055610725,
                            "remote_total": 0,
                            "remote_user": 0,
                            "remote_system": 0,
                        },
                    },
                },
            },
            {
                "tool": "iperf3",
                "test_type": {
                    "protocol": "UDP",
                },
                "time": {
                    "duration_sec": 1.0,
                },
                "metrics": {
                    "client": {
                        "sum_sent": {
                            "start": 0,
                            "end": 1.005694,
                            "seconds": 1.005694,
                            "bytes": 163840,
                            "bits_per_second": 1303299.0154062766,
                            "jitter_ms": 0,
                            "lost_packets": 0,
                            "packets": 5,
                            "lost_percent": 0,
                            "sender": "true",
                        },
                        "sum_received": {
                            "start": 0,
                            "end": 1.006723,
                            "seconds": 1.006723,
                            "bytes": 163840,
                            "bits_per_second": 1301966.8766880264,
                            "jitter_ms": 0.3490292816162109,
                            "lost_packets": 0,
                            "packets": 5,
                            "lost_percent": 0,
                            "sender": "false",
                        },
                        "cpu_utilization_percent": {
                            "host_total": 2.7494258492000685,
                            "host_user": 0.4593206399453781,
                            "host_system": 2.291366013376162,
                            "remote_total": 1.8860973187686196,
                            "remote_user": 0.772591857000993,
                            "remote_system": 1.1143992055610725,
                        },
                    },
                    "server": {
                        "sum_sent": {
                            "start": 0,
                            "end": 1.006723,
                            "seconds": 1.006723,
                            "bytes": 0,
                            "bits_per_second": 0,
                            "jitter_ms": 0,
                            "lost_packets": 0,
                            "packets": 0,
                            "lost_percent": 0,
                            "sender": "true",
                        },
                        "sum_received": {
                            "start": 0,
                            "end": 1.006723,
                            "seconds": 1.006723,
                            "bytes": 163840,
                            "bits_per_second": 1301966.8766880264,
                            "jitter_ms": 0.3490292816162109,
                            "lost_packets": 0,
                            "packets": 5,
                            "lost_percent": 0,
                            "sender": "false",
                        },
                        "cpu_utilization_percent": {
                            "host_total": 1.8860973187686196,
                            "host_user": 0.772591857000993,
                            "host_system": 1.1143992055610725,
                            "remote_total": 0,
                            "remote_user": 0,
                            "remote_system": 0,
                        },
                    },
                },
            },
        ),
        (
            {},
            {
                "tool": "iperf3",
                "test_type": {},
                "time": {},
                "metrics": {},
            },
        ),
    ],
    ids=[
        "Iperf3 adapter test.",
        "Empty metrics.",
    ],
)
def test_iperf3_parse_metrics(raw_metrics: dict[str, Any], expected: dict[str, Any]) -> None:
    result = Iperf3.split_result(raw_metrics=raw_metrics)
    assert result == expected


@pytest.mark.parametrize(
    ("raw_metrics", "expected"),
    [
        (
            {
                "title": "2026-04-05-2206",
                "last_modified": "2026-04-05 22:12:17",
                "description": "qemu testing on poky 5.2.4 via the Phoronix Test Suite.",
                "systems": {
                    "2026-04-05 22:06": {
                        "identifier": "2026-04-05 22:06",
                        "hardware": {
                            "Processor": "Intel Xeon E3-12xx v2 (4 Cores)",
                            "Motherboard": "QEMU Standard PC (Q35 + ICH9 2009)",
                            "Chipset": "Intel 82G33/G31/P35/P31 + ICH9",
                            "Memory": "1 x 2 GB RAM QEMU",
                            "Disk": "10GB",
                            "Graphics": "bochs-drmdrmfb",
                            "Monitor": "QEMU Monitor",
                            "Network": "Red Hat Virtio device",
                        },
                        "software": {
                            "OS": "poky 5.2.4",
                            "Kernel": "6.12.47-yocto-standard (x86_64)",
                            "Compiler": "GCC 14.3.0",
                            "File-System": "ext4",
                            "Screen Resolution": "1280x800",
                            "System Layer": "qemu",
                        },
                        "user": "root",
                        "timestamp": "2026-04-05 22:07:04",
                        "client_version": "10.8.4",
                        "data": {
                            "compiler-configuration": "",
                            "cpu-microcode": "0x1",
                            "security": "",
                        },
                    },
                },
                "results": {
                    "d14fab923a8a05c721a245a14d1b704edb4f77f8": {
                        "identifier": "pts/ctx-clock-1.0.0",
                        "title": "ctx_clock",
                        "description": "Context Switch Time",
                        "scale": "Clocks",
                        "proportion": "LIB",
                        "display_format": "BAR_GRAPH",
                        "results": {
                            "2026-04-05 22:06": {
                                "value": 19585,
                                "raw_values": [
                                    19573,
                                    19596,
                                ],
                                "test_run_times": [
                                    154.03,
                                    150.62,
                                ],
                                "details": {
                                    "compiler-options": {
                                        "compiler-type": "CC",
                                        "compiler": "gcc",
                                        "compiler-options": "",
                                    },
                                },
                            },
                        },
                    },
                },
            },
            {
                "tool": "pts",
                "test_type": {
                    "identifier": "pts/ctx-clock-1.0.0",
                },
                "time": {
                    "timestamp": "2026-04-05 22:07:04",
                },
                "metrics": {
                    "value": 19585,
                    "raw_values": [
                        19573,
                        19596,
                    ],
                    "test_run_times": [
                        154.03,
                        150.62,
                    ],
                },
            },
        ),
        (
            {},
            {
                "tool": "pts",
                "test_type": {},
                "time": {},
                "metrics": {},
            },
        ),
    ],
    ids=[
        "PTS adapter test.",
        "Empty metrics.",
    ],
)
def test_pts_parse_metrics(raw_metrics: dict[str, Any], expected: dict[str, Any]) -> None:
    result = PhoronixTestSuite.split_result(raw_metrics=raw_metrics)
    assert result == expected


@pytest.mark.parametrize(
    ("raw_metrics", "expected"),
    [
        (
            {
                "results": [
                    {
                        "test_fqn": "pth_str01",
                        "status": "pass",
                        "test": {
                            "command": "pth_str01",
                            "arguments": [],
                            "log": "pth_str01    0  TINFO  :  Allocating 85 nodes.",
                            "retval": ["0"],
                            "duration": 0.16393470764160156,
                            "failed": 0,
                            "passed": 1,
                            "broken": 0,
                            "skipped": 0,
                            "warnings": 0,
                            "result": "pass",
                        },
                    },
                    {
                        "test_fqn": "pth_str02",
                        "status": "pass",
                        "test": {
                            "command": "pth_str02",
                            "arguments": ["-n1000"],
                            "log": "pth_str02    0  TINFO  :  Creating 1000 threads.",
                            "retval": ["0"],
                            "duration": 1.8436052799224854,
                            "failed": 0,
                            "passed": 1,
                            "broken": 0,
                            "skipped": 0,
                            "warnings": 0,
                            "result": "pass",
                        },
                    },
                    {
                        "test_fqn": "pth_str03",
                        "status": "pass",
                        "test": {
                            "command": "pth_str03",
                            "arguments": [],
                            "log": "pth_str03    0  TINFO  :  Allocating 85 nodes.",
                            "retval": ["0"],
                            "duration": 0.2942326068878174,
                            "failed": 0,
                            "passed": 1,
                            "broken": 0,
                            "skipped": 0,
                            "warnings": 0,
                            "result": "pass",
                        },
                    },
                ],
                "stats": {
                    "runtime": 2.3017725944519043,
                    "passed": 3,
                    "failed": 0,
                    "broken": 0,
                    "skipped": 0,
                    "warnings": 0,
                },
                "environment": {
                    "distribution": "poky",
                    "distribution_version": "5.2.4",
                    "kernel": "Linux 6.12.47-yocto-standard #1 SMP PREEMPT_DYNAMIC Mon Sep 15",
                    "arch": "x86_64",
                    "cpu": "unknown",
                    "swap": "0 kB",
                    "RAM": "2025736 kB",
                },
            },
            {
                "tool": "kirk",
                "test_type": {},
                "time": {
                    "duration_sec": 2.30,
                },
                "metrics": {
                    "0": {
                        "test": "pth_str01",
                        "status": "pass",
                        "arguments": [],
                        "log": "pth_str01    0  TINFO  :  Allocating 85 nodes.",
                        "retval": ["0"],
                        "duration": 0.16393470764160156,
                    },
                    "1": {
                        "test": "pth_str02",
                        "status": "pass",
                        "arguments": ["-n1000"],
                        "log": "pth_str02    0  TINFO  :  Creating 1000 threads.",
                        "retval": ["0"],
                        "duration": 1.8436052799224854,
                    },
                    "2": {
                        "test": "pth_str03",
                        "status": "pass",
                        "arguments": [],
                        "log": "pth_str03    0  TINFO  :  Allocating 85 nodes.",
                        "retval": ["0"],
                        "duration": 0.2942326068878174,
                    },
                    "summary": {
                        "passed": 3,
                        "failed": 0,
                        "broken": 0,
                        "skipped": 0,
                        "warnings": 0,
                    },
                },
            },
        ),
        (
            {},
            {
                "tool": "kirk",
                "test_type": {},
                "time": {},
                "metrics": {},
            },
        ),
    ],
    ids=[
        "Kirk adapter test.",
        "Empty metrics.",
    ],
)
def test_kirk_parse_metrics(raw_metrics: dict[str, Any], expected: dict[str, Any]) -> None:
    result = Kirk.split_result(raw_metrics=raw_metrics)
    assert result == expected


@pytest.mark.parametrize(
    ("raw_metrics", "expected"),
    [
        (
            {
                "fio version": "fio-3.39",
                "timestamp": 1775426714,
                "timestamp_ms": 1775426714124,
                "time": "Sun Apr  5 22:05:14 2026",
                "jobs": [
                    {
                        "jobname": "rand_write_4k",
                        "groupid": 0,
                        "job_start": 1775426708791,
                        "error": 0,
                        "eta": 0,
                        "elapsed": 6,
                        "job options": {
                            "name": "rand_write_4k",
                            "numjobs": "1",
                            "size": "100MB",
                            "rw": "randwrite",
                            "ioengine": "libaio",
                            "direct": "1",
                            "directory": "",
                            "bs": "4k",
                            "iodepth": "1",
                            "group_reporting": "",
                            "time_based": "",
                            "runtime": "5",
                            "unlink": "1",
                            "log_avg_msec": "1000",
                            "write_bw_log": "",
                            "write_iops_log": "",
                            "write_lat_log": "",
                        },
                        "read": {
                            "io_bytes": 0,
                            "io_kbytes": 0,
                            "bw_bytes": 0,
                            "bw": 0,
                            "iops": 0,
                            "runtime": 0,
                            "total_ios": 0,
                            "short_ios": 0,
                            "drop_ios": 0,
                            "slat_ns": {"min": 0, "max": 0, "mean": 0, "stddev": 0, "N": 0},
                            "clat_ns": {"min": 0, "max": 0, "mean": 0, "stddev": 0, "N": 0},
                            "lat_ns": {"min": 0, "max": 0, "mean": 0, "stddev": 0, "N": 0},
                            "bw_min": 0,
                            "bw_max": 0,
                            "bw_agg": 0,
                            "bw_mean": 0,
                            "bw_dev": 0,
                            "bw_samples": 0,
                            "iops_min": 0,
                            "iops_max": 0,
                            "iops_mean": 0,
                            "iops_stddev": 0,
                            "iops_samples": 0,
                        },
                        "write": {
                            "io_bytes": 177381376,
                            "io_kbytes": 173224,
                            "bw_bytes": 35469181,
                            "bw": 34637,
                            "iops": 8659.468106,
                            "runtime": 5001,
                            "total_ios": 43306,
                            "short_ios": 0,
                            "drop_ios": 0,
                            "slat_ns": {
                                "min": 47433,
                                "max": 6555649,
                                "mean": 66903.275989,
                                "stddev": 84217.080536,
                                "N": 43306,
                            },
                            "clat_ns": {
                                "min": 23757,
                                "max": 1078252,
                                "mean": 34432.038678,
                                "stddev": 20213.463806,
                                "N": 43306,
                                "percentile": {
                                    "1.000000": 24960,
                                    "5.000000": 25984,
                                    "10.000000": 26496,
                                    "20.000000": 28288,
                                    "30.000000": 29824,
                                    "40.000000": 30336,
                                    "50.000000": 30336,
                                    "60.000000": 30592,
                                    "70.000000": 30848,
                                    "80.000000": 32128,
                                    "90.000000": 39168,
                                    "95.000000": 48896,
                                    "99.000000": 130560,
                                    "99.500000": 146432,
                                    "99.900000": 197632,
                                    "99.950000": 252928,
                                    "99.990000": 423936,
                                },
                            },
                            "lat_ns": {
                                "min": 72662,
                                "max": 6604084,
                                "mean": 101335.314668,
                                "stddev": 87176.963031,
                                "N": 43306,
                            },
                            "bw_min": 34042,
                            "bw_max": 35684,
                            "bw_agg": 100,
                            "bw_mean": 34656.8,
                            "bw_dev": 648.340343,
                            "bw_samples": 5,
                            "iops_min": 8511,
                            "iops_max": 8922,
                            "iops_mean": 8664.4,
                            "iops_stddev": 162.336995,
                            "iops_samples": 5,
                        },
                        "trim": {
                            "io_bytes": 0,
                            "io_kbytes": 0,
                            "bw_bytes": 0,
                            "bw": 0,
                            "iops": 0,
                            "runtime": 0,
                            "total_ios": 0,
                            "short_ios": 0,
                            "drop_ios": 0,
                            "slat_ns": {"min": 0, "max": 0, "mean": 0, "stddev": 0, "N": 0},
                            "clat_ns": {"min": 0, "max": 0, "mean": 0, "stddev": 0, "N": 0},
                            "lat_ns": {"min": 0, "max": 0, "mean": 0, "stddev": 0, "N": 0},
                            "bw_min": 0,
                            "bw_max": 0,
                            "bw_agg": 0,
                            "bw_mean": 0,
                            "bw_dev": 0,
                            "bw_samples": 0,
                            "iops_min": 0,
                            "iops_max": 0,
                            "iops_mean": 0,
                            "iops_stddev": 0,
                            "iops_samples": 0,
                        },
                        "sync": {
                            "total_ios": 0,
                            "lat_ns": {"min": 0, "max": 0, "mean": 0, "stddev": 0, "N": 0},
                        },
                        "job_runtime": 5000,
                        "usr_cpu": 42.62,
                        "sys_cpu": 57.3,
                        "ctx": 21,
                        "majf": 0,
                        "minf": 44,
                        "iodepth_level": {
                            "1": 100,
                            "2": 0,
                            "4": 0,
                            "8": 0,
                            "16": 0,
                            "32": 0,
                            ">=64": 0,
                        },
                        "iodepth_submit": {
                            "0": 0,
                            "4": 100,
                            "8": 0,
                            "16": 0,
                            "32": 0,
                            "64": 0,
                            ">=64": 0,
                        },
                        "iodepth_complete": {
                            "0": 0,
                            "4": 100,
                            "8": 0,
                            "16": 0,
                            "32": 0,
                            "64": 0,
                            ">=64": 0,
                        },
                        "latency_ns": {
                            "2": 0,
                            "4": 0,
                            "10": 0,
                            "20": 0,
                            "50": 0,
                            "100": 0,
                            "250": 0,
                            "500": 0,
                            "750": 0,
                            "1000": 0,
                        },
                        "latency_us": {
                            "2": 0,
                            "4": 0,
                            "10": 0,
                            "20": 0,
                            "50": 95.155406,
                            "100": 1.537893,
                            "250": 3.253591,
                            "500": 0.050801,
                            "750": 0,
                            "1000": 0,
                        },
                        "latency_ms": {
                            "2": 0.01,
                            "4": 0,
                            "10": 0,
                            "20": 0,
                            "50": 0,
                            "100": 0,
                            "250": 0,
                            "500": 0,
                            "750": 0,
                            "1000": 0,
                            "2000": 0,
                            ">=2000": 0,
                        },
                        "latency_depth": 1,
                        "latency_target": 0,
                        "latency_percentile": 100,
                        "latency_window": 0,
                    },
                ],
            },
            {
                "tool": "fio",
                "test_type": {
                    "name": "rand_write_4k",
                    "size": "100MB",
                    "rw": "randwrite",
                    "ioengine": "libaio",
                    "bs": "4k",
                },
                "time": {
                    "timestamp": 1775426714,
                    "time": "Sun Apr  5 22:05:14 2026",
                    "job_runtime": 5000,
                },
                "metrics": {
                    "read": {
                        "io_bytes": 0,
                        "io_kbytes": 0,
                        "bw_bytes": 0,
                        "bw": 0,
                        "iops": 0,
                        "runtime": 0,
                        "total_ios": 0,
                        "short_ios": 0,
                        "drop_ios": 0,
                        "slat_ns": {
                            "min": 0,
                            "max": 0,
                            "mean": 0,
                            "stddev": 0,
                            "N": 0,
                        },
                        "clat_ns": {
                            "min": 0,
                            "max": 0,
                            "mean": 0,
                            "stddev": 0,
                            "N": 0,
                        },
                        "lat_ns": {
                            "min": 0,
                            "max": 0,
                            "mean": 0,
                            "stddev": 0,
                            "N": 0,
                        },
                        "bw_min": 0,
                        "bw_max": 0,
                        "bw_agg": 0,
                        "bw_mean": 0,
                        "bw_dev": 0,
                        "bw_samples": 0,
                        "iops_min": 0,
                        "iops_max": 0,
                        "iops_mean": 0,
                        "iops_stddev": 0,
                        "iops_samples": 0,
                    },
                    "write": {
                        "io_bytes": 177381376,
                        "io_kbytes": 173224,
                        "bw_bytes": 35469181,
                        "bw": 34637,
                        "iops": 8659.468106,
                        "runtime": 5001,
                        "total_ios": 43306,
                        "short_ios": 0,
                        "drop_ios": 0,
                        "slat_ns": {
                            "min": 47433,
                            "max": 6555649,
                            "mean": 66903.275989,
                            "stddev": 84217.080536,
                            "N": 43306,
                        },
                        "clat_ns": {
                            "min": 23757,
                            "max": 1078252,
                            "mean": 34432.038678,
                            "stddev": 20213.463806,
                            "N": 43306,
                            "percentile": {
                                "1.000000": 24960,
                                "5.000000": 25984,
                                "10.000000": 26496,
                                "20.000000": 28288,
                                "30.000000": 29824,
                                "40.000000": 30336,
                                "50.000000": 30336,
                                "60.000000": 30592,
                                "70.000000": 30848,
                                "80.000000": 32128,
                                "90.000000": 39168,
                                "95.000000": 48896,
                                "99.000000": 130560,
                                "99.500000": 146432,
                                "99.900000": 197632,
                                "99.950000": 252928,
                                "99.990000": 423936,
                            },
                        },
                        "lat_ns": {
                            "min": 72662,
                            "max": 6604084,
                            "mean": 101335.314668,
                            "stddev": 87176.963031,
                            "N": 43306,
                        },
                        "bw_min": 34042,
                        "bw_max": 35684,
                        "bw_agg": 100,
                        "bw_mean": 34656.8,
                        "bw_dev": 648.340343,
                        "bw_samples": 5,
                        "iops_min": 8511,
                        "iops_max": 8922,
                        "iops_mean": 8664.4,
                        "iops_stddev": 162.336995,
                        "iops_samples": 5,
                    },
                    "trim": {
                        "io_bytes": 0,
                        "io_kbytes": 0,
                        "bw_bytes": 0,
                        "bw": 0,
                        "iops": 0,
                        "runtime": 0,
                        "total_ios": 0,
                        "short_ios": 0,
                        "drop_ios": 0,
                        "slat_ns": {
                            "min": 0,
                            "max": 0,
                            "mean": 0,
                            "stddev": 0,
                            "N": 0,
                        },
                        "clat_ns": {
                            "min": 0,
                            "max": 0,
                            "mean": 0,
                            "stddev": 0,
                            "N": 0,
                        },
                        "lat_ns": {
                            "min": 0,
                            "max": 0,
                            "mean": 0,
                            "stddev": 0,
                            "N": 0,
                        },
                        "bw_min": 0,
                        "bw_max": 0,
                        "bw_agg": 0,
                        "bw_mean": 0,
                        "bw_dev": 0,
                        "bw_samples": 0,
                        "iops_min": 0,
                        "iops_max": 0,
                        "iops_mean": 0,
                        "iops_stddev": 0,
                        "iops_samples": 0,
                    },
                },
            },
        ),
        (
            {},
            {
                "tool": "fio",
                "test_type": {},
                "time": {},
                "metrics": {},
            },
        ),
    ],
    ids=[
        "Fio adapter test.",
        "Empty metrics.",
    ],
)
def test_fio_parse_metrics(raw_metrics: dict[str, Any], expected: dict[str, Any]) -> None:
    result = Fio.split_result(raw_metrics=raw_metrics)
    assert result == expected
