name: Check source code

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'

  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

  workflow_dispatch:

jobs:
  check-code:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Check source code with pre-commit hooks
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        make pre-commit-check
    - name: Run unit tests
      run: |
        make unit-test
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@v1
      with:
        pytest-xml-coverage-path: ./test/pytest-coverage.xml
